### ISSUE TITLE
Question about VAE loss computation

### ISSUE THREAD

**Issue by ZhuFengdaaa** [wyndwarrior/Sectar#4]
I don't understand why you use `x[:, self.step_dim:]` rather than `x[:, :self.step_dim]` to compute MSE. As far as I know, `x[:, :self.step_dim]` is the observation for the total trajectory. What's the meaning of `x[:, self.step_dim:]`? 
https://github.com/wyndwarrior/Sectar/blob/master/traj2vec/algos/vae_bc.py#L90

Thanks!

**Comment by jcoreyes** [comment]
step_dim will be the dimension of a single observation. We're predicting the whole trajectory not including the first observation so this will be x[:, self.step_dim:] since this will not include the first observation in the trajectory.

**Comment by ZhuFengdaaa** [comment]
x[:, :self.step_dim] is the initial state for decoding and x[:, self.step_dim:] is the label. Got it! Thanks for your answer!
